### ISSUE TITLE
Quest Tracker

### ISSUE THREAD

**Issue by TheRealRaxion** [EthanCentaurai/Chinchilla#23]
Not sure if this is an issue with Chinchilla, interference from another addon or something entirely different.
I have "Quest Tracker" set to enabled, and use a custom position (vertical), and every time I log in/go from one zone to another, the quest tracker bumps down, as if completely disregarding the position I set in the options. Un-ticking and re-ticking "Enabled" moves it back to the set position, but I have to do this all the time.

Thanks in advance!

**Comment by EthanCentaurai** [comment]
I'm inclined to say it's interference with other addons.

There was an issue prior to v2.9 where the tracker would reset to its default position when changing a zone due to some dodgy code in Blizzard's action bars (don't ask). I'm assuming you've got the latest update installed?

I have also recently noticed that some databroker display addons such as Bazooka and Chocolate Bar have been causing a few problems.  If you have one of those, turn off any "readjust frames" or similarly worded options. That might do the trick but I can't guarantee anything.

**Comment by TheRealRaxion** [comment]
Not using any of those, but I found out what was causing it: MoveAnything.
Which makes perfect sense, and I honestly don't know why I didn't look more into it before posting >.<
Luckily I could disable only the tracker part of MoveAnything and not the entire addon!
Thanks!
